cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

sox_backend/urls.py
from django.contrib import admin
from django.urls import path, include

# from sox.shop.views import sox_detail, index

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('payment.urls')),
    path('coupons/', include('coupons.urls')),
    path('', include('shop.urls')),
]

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField()
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Sox
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Sox, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Sox, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends 'shop/index.html' %}
{% load static %}
{% block title %} Shopping cart {% endblock title %}

{% block content %}
  <section class="page-cart page-main__content page-main--top">
    <div class="page-cart__container page-container">
      <h1 class="page-cart__title page-text-h1">Shopping cart</h1>
      <!--  Если нет товара, то вывести нижнию надпись с кнопкой "Continue shopping" -->
      {#      <h2 class=" page-text-h2">You have nothing in your shopping cart.</h2>#}
      <!--  end -->
      <div class="page-cart__table">
        <div class="page-cart__table-wrapper">
          <div class="page-cart__table-wrapper-container">
            <div class="page-cart__thead">
              <div class="page-cart__table-cell page-cart__table-cell--remove">
                <p class="page-cart__thead-text">&nbsp;</p>
              </div>
              <div class="page-cart__table-cell page-cart__table-cell--image">
                <p class="page-cart__thead-text">Image</p>
              </div>
              <div class="page-cart__table-cell page-cart__table-cell--product">
                <p class="page-cart__thead-text">Product</p>
              </div>
              <div class="page-cart__table-cell">
                <p class="page-cart__thead-text">Quantity</p>
              </div>
              <div class="page-cart__table-cell page-cart__table-cell--uprice">
                <p class="page-cart__thead-text">Unit price</p>
              </div>
              <div class="page-cart__table-cell page-cart__table-cell--price">
                <p class="page-cart__thead-text">Price</p>
              </div>
            </div>
            <div class="page-cart__tbody">
              {% for item in cart %}
                {% with product=item.product %}
                  <div class="page-cart__tbody-container">
                    <div class="page-cart__tbody-cell page-cart__table-cell page-cart__table-cell--remove">
                      <a href="{% url 'cart:cart_remove' product.id %}">
                        <svg
                            height="15"
                            width="15"
                            viewBox="0 0 420 420"
                            xmlns="http://www.w3.org/2000/svg">
                          <path
                              d="M243.188 182.86L356.32 69.726c12.5-12.5 12.5-32.766 0-45.247L341.238 9.398c-12.504-12.503-32.77-12.503-45.25 0L182.86 122.528 69.727 9.374c-12.5-12.5-32.766-12.5-45.247 0L9.375 24.457c-12.5 12.504-12.5 32.77 0 45.25l113.152 113.152L9.398 295.99c-12.503 12.503-12.503 32.769 0 45.25l15.082 15.08c12.5 12.5 32.766 12.5 45.247 0l113.132-113.132L295.99 356.32c12.503 12.5 32.769 12.5 45.25 0l15.081-15.082c12.5-12.504 12.5-32.77 0-45.25zm0 0"/>
                        </svg>
                      </a>
                    </div>
                    <div class="page-cart__tbody-cell page-cart__table-cell page-cart__table-cell--image">
                      <a href="{{ product.get_absolute_url }}">
                        <img src="{{ product.image.url }}">
                      </a>
                    </div>
                    <div class="page-cart__tbody-cell page-cart__table-cell page-cart__table-cell--product">
                      <p>{{ product.name }}</p>
                    </div>
                    <div class="page-cart__tbody-cell page-cart__tbody-quantity page-cart__table-cell">
                      <form action="{% url 'cart:cart_add' product.id %}" method="post">
                        <!-- <input type="number" min="0" value="1"> -->
                        {{ item.update_quantity_form.quantity }}
                        {{ item.update_quantity_form.update }}
                        <input class="page-cart__btn-update btn btn-secondary" type="submit" value="Update">
                        {% csrf_token %}
                      </form>
                    </div>
                    <div class="num page-cart__tbody-cell page-cart__table-cell page-cart__table-cell--uprice">
                      ${{ item.price }}</div>
                    <div class="num page-cart__tbody-cell page-cart__table-cell page-cart__table-cell--price">
                      ${{ item.total_price }}</div>
                  </div>
                {% endwith %}
              {% endfor %}
            </div>
          </div>
          <!-- end table-wrapper -->
        </div>
        <!-- end table-wrapper-container -->
      </div>
      <!-- end .page-cart__table -->

      <div class="page-cart__coupon">
        <h3 class="page-cart__coupon-title page-text page-text-h3">Apply a coupon</h3>
        <form class="page-cart__coupon-form" action="{% url 'coupons:apply' %}" method="post">
          {{ coupon_apply_form }}
          <input class="page-cart__btn-update btn btn-secondary" type="submit" value="Apply">
          {% csrf_token %}
        </form>

        {% if cart.coupon %}
          <p>Subtotal</p>
          <p>{{ cart.get_total_price|floatformat:"2" }}</p>

          <p>{{ cart.coupon.code }} coupon ({{ cart.coupon.discount }}% off)</p>
          <p>-$ {{ cart.get_discount|floatformat:"2" }}</p>
        {% endif %}
        <p>${{ cart.get_total_price_after_discount|floatformat:"2" }}</p>
      </div>
      <!-- end .page-cart__coupon -->

      <div class="page-cart__total">
        <p class="page-cart__total-text page-text">Total:</p>
        <p class="page-cart__total-num page-text">
          <b>${{ cart.get_total_price }}</b>
        </p>
      </div>
      <!-- end .page-cart__total -->

      <!--  Если нет товара, то вывести верхнюю надпись с кнопкой "Continue shopping" -->
      <!-- <div class="page-cart__continue">
        <a class="page-cart__action-btn btn btn-secondary" href="{% url "sox_list" %}">Continue shopping</a>
      </div> -->
      <!-- end -->

      <div class="page-cart__checkout">
        <a class="page-cart__action-btn btn btn-primary" href="{% url 'orders:order_create' %}">Checkout</a>
      </div>
    </div>
  </section>

{% endblock content %}