cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from rest_framework import routers

from .views import index, sox_detail, our_sox, sox_list, sale, gallery

urlpatterns = [
    path('sale', sale, name='sale'),
    path('gallery', gallery, name='gallery'),
    path('our_sox', our_sox, name='our_sox'),
    path('shop', sox_list, name='sox_list'),
    path('<slug:category_slug>', index, name='sox_list_by_category'),
    path('shop/<int:id>', sox_detail, name='sox_detail'),
    path('', index, name='home'),
]

sox_backend/urls.py
from django.contrib import admin
from django.urls import path, include

# from sox.shop.views import sox_detail, index

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payment/', include('payment.urls')),
    path('coupons/', include('coupons.urls')),
    path('', include('shop.urls')),
]

shop/models.py
from PIL import Image
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('sox_list_by_category', args=[self.slug])


class Sox(models.Model):
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    description = models.TextField()
    price = models.TextField()
    image = models.ImageField(upload_to='static/sox')
    fabrics = models.TextField()
    size = models.TextField()

    class Meta:
        verbose_name = verbose_name_plural = 'Sox'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            width, height = img.size
            ratio = round(height / width)
            newheight = ratio * 300

            img = img.resize((500, 500), Image.ANTIALIAS)
            img.save(self.image.path)

    def get_absolute_url(self):
        return reverse('sox_detail', args=[self.id])

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField()
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Sox, Category
from cart.forms import CartAddProductForm


def index(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    sox = Sox.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sox = sox.filter(category=category)
    return render(request, 'shop/home.html', {'category': category, 'categories': categories, 'sox': sox})


def sox_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    sox = Sox.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        sox = sox.filter(category=category)
    return render(request, 'shop/Shop.html', {'category': category, 'categories': categories, 'sox': sox})


def sox_detail(request, id):
    sox = get_object_or_404(Sox, id=id)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/sox_detail.html', {'sox': sox, 'cart_product_form': cart_product_form})


def our_sox(request):
    sox = Sox.objects.all()
    return render(request, 'shop/Our-sox.html', {'sox': sox})


def sale(request):
    return render(request, 'shop/Sale.html')

def gallery(request):
    return render(request, 'shop/Gallery.html')

shop/templates/shop/Gallery.html
{% extends 'shop/index.html' %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block content %}
  <main class="page-main js-page-main">
    <section class="page-gallery page-main__content">
      <div class="page-container page-gallery__container">
        <div class="page-gallery__list js-gallery-list">
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery1.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery1.jpg" alt="image1" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery2.jpg' %})"
              data-mfp-src=" .js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery2.jpg" alt="image2" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery3.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery3.jpg" alt="image3" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery4.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery4.jpg" alt="image4" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery5.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery5.jpg" alt="image5" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery6.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery6.jpg" alt="image6" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery7.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery7.jpg" alt="image7" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery8.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery8.jpg" alt="image8" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery9.jpg' %})"
              data-mfp-src=".js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery9.jpg" alt="image9" /> -->#}
          </figure>
          <figure
              class="page-gallery__list-item js-gallery-list-item"
              style="background-image: url({% static 'img/img-gallery10.jpg' %})"
              data-mfp-src=" .js-gallery-page-swiper">
            {# <img src="{% static 'img/img-gallery10.jpg" alt="image10" /> -->#}
          </figure>
        </div>
      </div>
    </section>
    <!-- end .page-gallery .page-main__content -->

    <!-- end .page-subscribe .page-main__content -->
  </main>
  <!-- end .page-main -->

  <section class="js-gallery-page-swiper" style="display: none;">
    <div
        class="page-gallery__gallery-slides swiper-container js-gallery-top-swiper"
    >
      <div class="swiper-wrapper">
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery1.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery2.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery3.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery4.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery5.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery6.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery7.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery8.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery9.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery10.jpg' %})"
        ></figure>
      </div>
      <!-- Add Arrows -->
      <div class="swiper-button-next swiper-button-white"></div>
      <div class="swiper-button-prev swiper-button-white"></div>
    </div>
    <div
        class="page-gallery__thumbs swiper-container js-gallery-thumbs-swiper"
    >
      <div class="swiper-wrapper">
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery1.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery2.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery3.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery4.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery5.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery6.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery7.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery8.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" 
            style="background-image: url({% static 'img/img-gallery9.jpg' %})"
        ></figure>
        <figure
            class="swiper-slide" style="background-image: url({% static 'img/img-gallery10.jpg' %})"
        ></figure>
      </div>
    </div>
  </section>
  <!-- end .js-gallery-page-swiper -->
{% endblock content %}

shop/templates/shop/Sale.html
{% extends 'shop/index.html' %}
{% load static %}

{% block title %} Sale {% endblock title %}
{% block content %}
<!-- end .page-header -->
<main style='overflow-x:hidden;' class="page-main">
  <section  class="wow animate__animated animate__fadeIn  page-sale page-main__content page-main--top">
    <div class="page-container">
      <div class="page-sale__container swiper-container js-salelist-swiper">
        <div class="page-sale__wrapper swiper-wrapper">
          <div class="page-sale__item swiper-slide">
            <h2 class="page-sale__title">Home SOX</h2>
            <div class="page-sale__top">
              <div
                  class="page-sale__cover"
                  style="background-image: url(./img/img-sale1.png)"
              ></div>
              <h1 class="page-sale__cost">CHF 11.00</h1>
              <p class="page-sale__subtitle">ONE SALE - HOME SOX</p>
            </div>
            <p class="page-main__text page-text page-text--highlight">
              <b>Created for home activity.</b>
            </p>
            <p class="page-text">
              <b>Fabrics:</b>
              <i
              >80% jacquard-half terry cotton, 20% spandex/elastane.
                Grips: PVC</i
              >
            </p>
            <ul class="page-sale__list">
              <li class="page-sale__list-item">Anti-slippery points</li>
              <li class="page-sale__list-item">
                Light and breathable fabrics
              </li>
              <li class="page-sale__list-item">Reinforced foot bed</li>
              <li class="page-sale__list-item">Special arch support</li>
              <li class="page-sale__list-item">Mid-weight</li>
            </ul>
          </div>
          <div class="page-sale__item swiper-slide">
            <h2 class="page-sale__title">Special Pack</h2>
            <div class="page-sale__top">
              <div
                  class="page-sale__cover"
                  style="background-image: url(./img/img-sale2.png)"
              ></div>
              <h1 class="page-sale__cost">CHF 39.00</h1>
              <p class="page-sale__subtitle">SPECIAL PACK WOMEN INCLUDES</p>
            </div>
            <p class="page-text">
              <b>Fabrics:</b>
              <i
              >80% jacquard-half terry cotton, 20% spandex/elastane.
                Grips: PVC</i
              >
            </p>
            <ul class="page-sale__list">
              <li class="page-sale__list-item">Ballet Grip - Pink</li>
              <li class="page-sale__list-item">Classic Grip - Pink</li>
              <li class="page-sale__list-item">Speedy sport - Grey</li>
            </ul>
            <p class="page-text">
              <b>Care:</b>
              <i
              >Machine wash at 40°C. Do not bleach. Do not dry clean.
                Tumble dry on a low setting.</i
              >
            </p>
          </div>
        </div>
        <!-- Sport antislippery socks - for your
          <strong><i class="page-text--highlight">pilates</i></strong
          >, <i>barre</i>,
          <strong><i class="page-text--highlight">trx</i></strong> and
          <strong><i class="page-text--highlight">yoga classes</i></strong>
        </h3> -->
      </div>
    </div>
  </section>
  <!-- end .page-shop .page-main__content -->
</main>

{% endblock content %}

shop/templates/shop/Shop.html
{% extends 'shop/index.html' %}
{% load static %}
{% block title %} Shop {% endblock title %}
{% block content %}
  <main class="page-main page-main--shop js-page-main">
    <section class="page-shop page-main__content page-main--top">
      <div class="page-shop__container page-container">
        <h3
            class="page-shop__title page-text page-text-h3 page-text--noweight"
        >
          Sport antislippery socks - for your
          <strong><i class="page-text--highlight">pilates</i></strong
          >, <i>barre</i>,
          <strong><i class="page-text--highlight">trx</i></strong> and
          <strong><i class="page-text--highlight">yoga classes</i></strong>
        </h3>
      </div>
    </section>
    <!-- end .page-shop .page-main__content -->

    <section class="page-shop page-main__content">
      <div class="page-shop__inner page-container">
        <div class="page-shop__filters">
          <div class="page-shop__products-title">
            <p>Swiss design</p>
          </div>
          <div class="page-shop__filters-list swiper--mob-show swiper-container js-shop-filters-swiper">
            <div class="page-shop__filters-wrapper swiper-wrapper">
              <div class="page-shop__filter-item swiper-slide">
                <p class="page-shop__filter-text page-shop__filter-text--active js-shop-filter"
                   data-filterkey="0">All</p>
              </div>
              {% for category in categories %}
                <div class="page-shop__filter-item swiper-slide">
                  <p class="page-shop__filter-text js-shop-filter"
                     data-filterkey="{{ category.slug }}">{{ category.name }}</p>
                </div>
              {% endfor %}
            </div>
          </div>
          <div class="page-shop__filters swiper--desk-show">
            <div class="page-shop__filters-wrapper">
              <div class="page-shop__filter-item">
                <p class="page-shop__filter-text page-shop__filter-text--active js-shop-filter"
                   data-filterkey="0">All</p>
              </div>
              {% for category in categories %}
                <div class="page-shop__filter-item swiper-slide">
                  <p class="page-shop__filter-text js-shop-filter"
                     data-filterkey="{{ category.slug }}">{{ category.name }}</p>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="page-shop__products js-is-qview" data-is-qview="false">
          {% for item in sox %}
            <div class="page-shop__product js-shop-product" data-filterid="{{ item.category.slug }}">
              <div class="page-shop__product-card">
                <a class="page-shop__card" href="{{ item.get_absolute_url }}">
                  <img class="page-shop__product-img" src="{{ item.image.url }}" alt=""/>
                </a>
                <button class="page-shop__qview-btn btn js-popup-qview-btn"
                        data-mfp-src=".js-popup-zoom-qview-card">Quick View
                </button>
              </div>
            </div>
          {% endfor %}
        </div>

        <div class="page-shop page-shop__popup-zoom js-popup-zoom-qview-card" style="display: none">
          <div class="page-shop__qview-box">
            <div class="page-shop__qview-container js-shop-qview-card-slick">
              {% for item in sox %}
                <div class="page-shop__qview">
                  <div class="page-shop__qview-container">
                    <div class="page-shop__qview-gallery">
                      <div class="js-zoom-card-slick">
                        <div class="page-shop__card-img-box js-card-zoom-img" data-src="https://unsplash.it/870/970">
                          <img class="page-shop__card-img" src="https://unsplash.it/1100/970" alt=""/>
                          {#<img class="page-shop__card-img" src="{{ item.image.url }}" alt=""/>#}
                        </div>
                        <!-- end  -->
                        <div class="js-card-zoom-img">
                          <img class="page-shop__card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                        <!-- end  -->
                        <div class="js-card-zoom-img">
                          <img class="page-shop__card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                        <!-- end -->
                        <div class="js-card-zoom-img">
                          <img class="page-shop__card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                        <!-- end -->
                      </div>
                      <!-- end of .js-zoom-card-swiper -->

                      <!-- Если 1 фотография, то скрыть нижний блок .page-shop__qview-card-thumbs -->
                      <div class="page-shop__qview-card-thumbs js-zoom-card-thumbs-slick">
                        <div class="page-shop__qview-card-thumb">
                          <img class="page-shop__qview-card-img" src="https://unsplash.it/870/870" alt=""/>
                          {#<img class="page-shop__qview-card-img" src="{{ item.image.url }}" alt=""/>#}
                        </div>
                        <!-- end of .swiper-slide -->
                        <div class="page-shop__qview-card-thumb">
                          <img class="page-shop__qview-card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                        <!-- end of .swiper-slide -->
                        <div class="page-shop__qview-card-thumb">
                          <img class="page-shop__qview-card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                        <!-- end of .swiper-slide -->
                        <div class="page-shop__qview-card-thumb">
                          <img class="page-shop__qview-card-img" src="{{ item.image.url }}" alt=""/>
                        </div>
                      </div>
                      <!-- end of .swiper-container .js-zoom-card-thumbs-swiper -->
                    </div>
                    <!-- end of .page-shop__qview-gallery -->
                    <div class="page-shop__qview-details">
                      <h1 class="page-shop__card-title">{{ item.title }}</h1>
                      <h2 class="page-shop__card-cost">CHF{{ item.price }}</h2>
                      <div class="page-shop__card-btn-container">
                        <button class="page-shop__card-add btn btn-primary">Add to card</button>
                      </div>
                      <p class="page-shop__card-excerpt page-text">{{ item.description }}</p>
                      <div class="page-shop__card-link-container">
                        <a class="page-shop__card-full-link" href="{{ item.get_absolute_url }}">View full link</a>
                      </div>
                    </div>
                    <!-- end of .page-shop__qview-details -->
                  </div>
                  <!-- end of .page-shop__container -->
                </div>
                <!-- end of .page-shop__qview swiper-slide -->
              {% endfor %}
            </div>
          </div>
          <!-- end .swiper-button-prev next -->
        </div>
      </div>
    </section>
    <!-- end .page-shop .page-main__content -->
  </main>
  <!-- end .page-main -->

  <div class="footer-message">
    <div class="footer-message__container page-container">
      <p class="footer-message__text">
        Delivery in <i class="page-text--highlight">SWITZERLAND</i> is free,
        fast and secure.
      </p>
      <button class="footer-message__close js-close-footer-msg">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="20"
            height="20"
            viewBox="0 0 25 25">
          <path fill-rule="evenodd" clip-rule="evenodd"
                d="M1.70711 0.292893C1.31658 -0.097631 0.683418 -0.097631 0.292893 0.292893C-0.097631 0.683417 -0.097631 1.31658 0.292893 1.70711L9.58736 11.0016L0.292893 20.296C-0.0976312 20.6866 -0.097631 21.3197 0.292893 21.7102C0.683418 22.1008 1.31658 22.1008 1.70711 21.7102L11.0016 12.4158L20.296 21.7102C20.6866 22.1008 21.3197 22.1008 21.7102 21.7102C22.1008 21.3197 22.1008 20.6866 21.7102 20.296L12.4158 11.0016L21.7102 1.70711C22.1008 1.31658 22.1008 0.683418 21.7102 0.292894C21.3197 -0.0976301 20.6866 -0.097631 20.296 0.292894L11.0016 9.58736L1.70711 0.292893Z"/>
        </svg>
      </button>
    </div>
  </div>

{% endblock content %}

shop/templates/shop/sox_detail.html
{% extends 'shop/index.html' %}
{% load static %}
{% block title %} {{ sox.title }} {% endblock title %}

{% block content %}
  <section class="page-shop page-main__content page-main--top">
    <div class="page-shop__container page-container">
      <div class="page-shop__qview-container">
        <div class="page-shop__qview-gallery page-shop__gallery">
          <div class="js-zoom-card-slick">
            <div class="" data-src="{{ sox.image.url }}">
              <img class="page-shop__card-img js-card-zoom-img" src="{{ sox.image.url }}" alt='{{ sox.title }}'>
            </div>
            <!-- end  -->
            <div class="" data-src="{{ sox.image.url }}">
              <img class="page-shop__card-img js-card-zoom-img" src="{{ sox.image.url }}" alt='{{ sox.title }}'>
            </div>
            <!-- end  -->
          </div>
          <!-- end of .js-zoom-card-swiper -->

          <!-- Если 1 фотография, то скрыть нижний блок .page-shop__qview-card-thumbs -->
          <div class="page-shop__qview-card-thumbs js-zoom-card-thumbs-slick">
            <div class="page-shop__qview-card-thumb">
              <img class="page-shop__qview-card-img" src="{{ sox.image.url }}" alt=""/>
            </div>
            <!-- end -->
            <div class="page-shop__qview-card-thumb">
              <img class="page-shop__qview-card-img" src="{{ sox.image.url }}" alt=""/>
            </div>
            <!-- end -->
          </div>
          <!-- end of .js-zoom-card-thumbs-swiper -->
        </div>
        <!-- end of .page-shop__qview-gallery -->
        <div class="page-shop__qview-details page-shop__details">
          <h1 class="page-shop__card-title">{{ sox.title }}</h1>
          <h2 class="page-shop__card-cost">CHF{{ sox.price }}</h2>
          <div class="page-shop__card-form-wrapper">
            <form class="page-shop__card-form" action="{% url 'cart:cart_add' sox.id %}" method="post">
              <div class="page-shop__card-form-row">
                {#                 {{ cart_product_form }}#}
                <input type="number" name="quantity" min="0" placeholder="Quantity" required="" id="id_quantity">
                {% csrf_token %}
              </div>
              <div class="page-shop__card-form-row">
                <select class="selectbox js-size-nice-select" name="size" id="id_s_size">
                  <option value="s" default hidden>Select a size</option>
                  <option value="s">S</option>
                  <option value="m">M</option>
                  <option value="xl">XL</option>
                </select>
              </div>
              <div class="page-shop__card-form-row">
                <input class="page-shop__card-add btn btn-primary" type="submit" value="Add to cart">
              </div>
              {% comment %}
              <label class="" for="id_quantity">
                <p class="page-text">Quantity:</p>
                <input type="number" name="quantity" min="0" required id="id_quantity">
              </label>
              <button class="page-shop__card-add btn btn-primary" type="submit">Add to card</button>
              {% endcomment %}
            </form>
          </div>
          <div class="accordion js-card-accordion">
            <h3 class="accordion__title">Description</h3>
            <div class="accordion__row">
              <p class="accordion__text">{{ sox.description|linebreaks }}</p>
            </div>
            <!-- / -->
            <h3 class="accordion__title">Fabrics</h3>
            <div class="accordion__row">
              <p class="accordion__text">{{ sox.fabrics }}</p>
            </div>
            <!-- / -->
            <h3 class="accordion__title">Size</h3>
            <div class="accordion__row">
              <p class="accordion__text">{{ sox.size }}</p>
            </div>
            <!-- / -->
          </div>
        </div>
        <!-- end of .page-shop__qview-details -->
      </div>
      <!-- end of .page-shop__container -->
    </div>
  </section>

{% endblock content %}
<!--
{% comment %}
<section class="page-shop page-main__content page-main--top">
    <div class="page-shop__container page-container">
      {{ sox.title }}
      <img src="{{ sox.image.url }}" alt='{{ sox.title }}'>
      {{ sox.price }}
      <form action="{% url 'cart:cart_add' sox.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
      </form>

      {{ sox.description|linebreaks }}
      {{ sox.fabrics }}
      {{ sox.size }}
    </div>
  </section>
  {% endcomment %}
-->